// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuiFd1b9ozeW24O55UmHdaVP20vCApj7g',
    appId: '1:914731140416:web:e938e7f67f73c373a126a5',
    messagingSenderId: '914731140416',
    projectId: 'autotrader-app-70a0f',
    authDomain: 'autotrader-app-70a0f.firebaseapp.com',
    storageBucket: 'autotrader-app-70a0f.appspot.com',
    measurementId: 'G-56EDXY5NWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVTIawdKozOPsqf6zy9W6At-DgDXJvGl4',
    appId: '1:914731140416:android:e45c61413321cb1ea126a5',
    messagingSenderId: '914731140416',
    projectId: 'autotrader-app-70a0f',
    storageBucket: 'autotrader-app-70a0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Y7UbX0hmvFT7Dreb1HzzP5OG9xhr_wQ',
    appId: '1:914731140416:ios:54e7b29b58345276a126a5',
    messagingSenderId: '914731140416',
    projectId: 'autotrader-app-70a0f',
    storageBucket: 'autotrader-app-70a0f.appspot.com',
    iosBundleId: 'com.example.lotosui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6Y7UbX0hmvFT7Dreb1HzzP5OG9xhr_wQ',
    appId: '1:914731140416:ios:eac77d0ed4776032a126a5',
    messagingSenderId: '914731140416',
    projectId: 'autotrader-app-70a0f',
    storageBucket: 'autotrader-app-70a0f.appspot.com',
    iosBundleId: 'com.example.lotosui.RunnerTests',
  );
}
